[package]
name = "ai-pad"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.38.0", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
windows-sys = { version = "0.61.2", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_System_Threading"] }

[[bin]]
name = "ai-pad-ctl"
path = "src/main.rs"

[[bin]]
name = "ai-pad-read"
path = "src/bin/read.rs"
