"""Inspect alpha and connected sprite bounds without modifying image files.

The generated sheets are design references with imperfect cell alignment.
Component bounds prevent clipping when previewing individual poses.
"""
import json
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import label, find_objects

ROOT = Path(__file__).parent


def inspect(path):
    rgba = np.asarray(Image.open(path).convert('RGBA'))
    alpha = rgba[:, :, 3]
    labels, _ = label(alpha >= 128)
    regions = []
    for index, region in enumerate(find_objects(labels), 1):
        if region is None:
            continue
        area = int(np.count_nonzero(labels[region] == index))
        if area < 1500:
            continue
        ys, xs = region
        regions.append({'x': xs.start, 'y': ys.start,
                        'width': xs.stop-xs.start, 'height': ys.stop-ys.start,
                        'area': area})
    # Sorting by top edge globally fails for low-profile sleeping poses.
    mid = alpha.shape[0] / 2
    regions.sort(key=lambda b: (0 if b['y'] + b['height']/2 < mid else 1, b['x']))
    border = np.concatenate([alpha[0], alpha[-1], alpha[:, 0], alpha[:, -1]])
    return {'size': [rgba.shape[1], rgba.shape[0]],
            'transparentFraction': round(float(np.mean(alpha == 0)), 4),
            'nearOpaqueFraction': round(float(np.mean(alpha >= 250)), 4),
            'intermediateAlphaFraction': round(float(np.mean((alpha > 0) & (alpha < 250))), 4),
            'visibleBorderPixels': int(np.count_nonzero(border >= 128)),
            'regions': regions}


if __name__ == '__main__':
    catalog = json.loads((ROOT/'catalog.json').read_text())
    result = []
    for cat in catalog['cats']:
        entry = {'id': cat['id'], 'name': cat['name']}
        for version, folder in [('original', ROOT), ('refined', ROOT/'v2')]:
            path = folder / cat['image']
            entry[version] = inspect(path)
        result.append(entry)
        print(cat['id'], 'regions', len(entry['refined']['regions']),
              'border', entry['refined']['visibleBorderPixels'])
    serialized = json.dumps(result, ensure_ascii=False, indent=2)
    (ROOT/'v2'/'audit.json').write_text(serialized+'\n')
    (ROOT/'v2'/'audit-data.js').write_text(
        '// Generated by audit-assets.py; image analysis only.\nwindow.catAudit = '+serialized+';\n')
