const CAT_BREEDS = {
  tabby: {
    id: 'cat-tabby',
    displayName: 'Tabby Cat',
    description: 'A high-resolution tabby cat companion with expressive status animations.',
    breed: 'tabby',
    style: 'smooth-scaled expressive orange tabby companion',
    recommendedUse: 'default pet, game reactions, and status feedback',
    pattern: 'tabby',
    shape: {
      faceWidth: 1.0,
      faceHeight: 1.0,
      earScale: 1.0,
      bodyWidth: 1.0,
      bodyHeight: 1.0,
      tailLength: 1.0,
      tailFluff: 1.0,
      pawScale: 1.0,
    },
    palette: {
      outline: '#3d2730',
      furDark: '#8e5b3d',
      fur: '#d88b52',
      furLight: '#ffd2a4',
      cream: '#fff0d6',
      blush: '#ff9db1',
      eye: '#1b2638',
      iris: '#416f95',
    },
    details: { eyeDx: 18, eyeRx: 10, eyeRy: 12, accent: 'freckles' },
  },
  calico: {
    id: 'cat-calico',
    displayName: 'Calico Cat',
    description: 'A high-resolution calico cat companion with warm patchwork markings.',
    breed: 'calico',
    style: 'smooth-scaled expressive calico companion with patchwork coat markings',
    recommendedUse: 'colorful pet, cheerful reactions, and cozy desktop feedback',
    pattern: 'calico',
    shape: {
      faceWidth: 1.02,
      faceHeight: 1.0,
      earScale: 0.98,
      bodyWidth: 1.02,
      bodyHeight: 1.0,
      tailLength: 1.04,
      tailFluff: 1.08,
      pawScale: 1.02,
    },
    palette: {
      outline: '#34262a',
      furDark: '#2f2928',
      fur: '#f0b36b',
      furLight: '#fff1df',
      cream: '#fff8ef',
      blush: '#ff9fb4',
      eye: '#233149',
      iris: '#4f7f88',
      irisAlt: '#8b6cc8',
      patchA: '#d98539',
      patchB: '#2c2726',
    },
    details: { eyeDx: 19, eyeRx: 10, eyeRy: 12, heterochromia: true, fluff: 0.25 },
  },
  siamese: {
    id: 'cat-siamese',
    displayName: 'Siamese Cat',
    description: 'A high-resolution Siamese cat companion with point-color face, ears, paws, and tail.',
    breed: 'siamese',
    style: 'smooth-scaled expressive Siamese companion with cool blue-eyed point markings',
    recommendedUse: 'elegant pet, focused states, and calm desktop feedback',
    pattern: 'point',
    shape: {
      faceWidth: 0.88,
      faceHeight: 1.04,
      earScale: 1.18,
      bodyWidth: 0.90,
      bodyHeight: 1.08,
      tailLength: 1.18,
      tailFluff: 0.72,
      pawScale: 0.88,
    },
    palette: {
      outline: '#352822',
      furDark: '#5a4035',
      fur: '#d9c1a0',
      furLight: '#ead8bd',
      cream: '#f5e6ce',
      blush: '#d99a9e',
      eye: '#17324d',
      iris: '#53a8c7',
      point: '#4a342d',
    },
    details: { eyeDx: 17, eyeRx: 9, eyeRy: 12, eyeYOffset: 1 },
  },
  tuxedo: {
    id: 'cat-tuxedo',
    displayName: 'Tuxedo Cat',
    description: 'A high-resolution tuxedo cat companion with sharp black-and-white contrast.',
    breed: 'tuxedo',
    style: 'smooth-scaled expressive tuxedo companion with white chest and face blaze',
    recommendedUse: 'crisp pet, terminal-adjacent themes, and status feedback',
    pattern: 'tuxedo',
    shape: {
      faceWidth: 0.98,
      faceHeight: 1.0,
      earScale: 1.0,
      bodyWidth: 1.0,
      bodyHeight: 1.02,
      tailLength: 0.98,
      tailFluff: 0.96,
      pawScale: 1.0,
    },
    palette: {
      outline: '#171a20',
      furDark: '#10141a',
      fur: '#202833',
      furLight: '#3a4654',
      cream: '#fff8ef',
      blush: '#f3a3b6',
      eye: '#101722',
      iris: '#83d0b5',
    },
    details: { eyeDx: 18, eyeRx: 10, eyeRy: 11, accent: 'bowtie' },
  },
  black: {
    id: 'cat-black',
    displayName: 'Black Cat',
    description: 'A high-resolution black cat companion with soft night-mode contrast.',
    breed: 'black',
    style: 'smooth-scaled expressive black cat companion with subtle charcoal highlights',
    recommendedUse: 'night mode pet, quiet focus, and compact desktop feedback',
    pattern: 'solid',
    shape: {
      faceWidth: 0.96,
      faceHeight: 0.98,
      earScale: 1.06,
      bodyWidth: 0.96,
      bodyHeight: 0.98,
      tailLength: 1.08,
      tailFluff: 0.92,
      pawScale: 0.95,
    },
    palette: {
      outline: '#080a10',
      furDark: '#11141d',
      fur: '#202638',
      furLight: '#3b435a',
      cream: '#4a5268',
      blush: '#a1748c',
      eye: '#0d1624',
      iris: '#e7d96f',
    },
    details: { eyeDx: 18, eyeRx: 10, eyeRy: 12, eyeYOffset: -1 },
  },
  white: {
    id: 'cat-white',
    displayName: 'White Cat',
    description: 'A high-resolution white cat companion with gentle pale coat shading.',
    breed: 'white',
    style: 'smooth-scaled expressive white cat companion with soft cream shadows',
    recommendedUse: 'minimal pet, gentle moods, and clean desktop feedback',
    pattern: 'solid',
    shape: {
      faceWidth: 1.06,
      faceHeight: 1.02,
      earScale: 0.92,
      bodyWidth: 1.04,
      bodyHeight: 1.0,
      tailLength: 0.95,
      tailFluff: 1.04,
      pawScale: 1.04,
    },
    palette: {
      outline: '#6d5960',
      furDark: '#d7c7bd',
      fur: '#f4e8dc',
      furLight: '#fff8ef',
      cream: '#ffffff',
      blush: '#ffb4c4',
      eye: '#263454',
      iris: '#7aa7d9',
    },
    details: { eyeDx: 19, eyeRx: 11, eyeRy: 12, fluff: 0.45 },
  },
  ginger: {
    id: 'cat-ginger',
    displayName: 'Ginger Cat',
    description: 'A high-resolution ginger cat companion with bright marmalade stripes.',
    breed: 'ginger',
    style: 'smooth-scaled cheerful ginger tabby companion with sunny orange stripes',
    recommendedUse: 'playful pet, upbeat reactions, and warm desktop feedback',
    pattern: 'tabby',
    shape: {
      faceWidth: 1.04,
      faceHeight: 1.0,
      earScale: 0.96,
      bodyWidth: 1.04,
      bodyHeight: 0.98,
      tailLength: 0.98,
      tailFluff: 1.12,
      pawScale: 1.04,
    },
    palette: {
      outline: '#432a27',
      furDark: '#a95e2e',
      fur: '#f08a36',
      furLight: '#ffc27a',
      cream: '#fff0cf',
      blush: '#ff9cad',
      eye: '#1c2a38',
      iris: '#5b9a68',
    },
    details: { eyeDx: 18, eyeRx: 10, eyeRy: 12, accent: 'freckles' },
  },
  gray: {
    id: 'cat-gray',
    displayName: 'Gray Cat',
    description: 'A high-resolution gray tabby cat companion with soft smoke stripes.',
    breed: 'gray',
    style: 'smooth-scaled cozy gray tabby companion with gentle smoke markings',
    recommendedUse: 'calm pet, neutral themes, and soft status feedback',
    pattern: 'tabby',
    shape: {
      faceWidth: 1.0,
      faceHeight: 1.02,
      earScale: 1.0,
      bodyWidth: 1.0,
      bodyHeight: 1.02,
      tailLength: 1.02,
      tailFluff: 1.0,
      pawScale: 1.0,
    },
    palette: {
      outline: '#30323a',
      furDark: '#68707e',
      fur: '#929cab',
      furLight: '#c8d1dc',
      cream: '#eef1f4',
      blush: '#f3a4b8',
      eye: '#182133',
      iris: '#6f93b4',
    },
    details: { eyeDx: 17, eyeRx: 9, eyeRy: 12, fluff: 0.1 },
  },
  cream: {
    id: 'cat-cream',
    displayName: 'Cream Cat',
    description: 'A high-resolution cream cat companion with soft vanilla shading.',
    breed: 'cream',
    style: 'smooth-scaled gentle cream companion with vanilla coat shadows',
    recommendedUse: 'cozy pet, low-contrast themes, and gentle moods',
    pattern: 'solid',
    shape: {
      faceWidth: 1.08,
      faceHeight: 1.02,
      earScale: 0.9,
      bodyWidth: 1.08,
      bodyHeight: 0.98,
      tailLength: 0.94,
      tailFluff: 1.1,
      pawScale: 1.08,
    },
    palette: {
      outline: '#8a6358',
      furDark: '#d3aa82',
      fur: '#f0d0a4',
      furLight: '#fff0cf',
      cream: '#fff8e6',
      blush: '#ffacbd',
      eye: '#26304a',
      iris: '#7b8fc6',
    },
    details: { eyeDx: 20, eyeRx: 11, eyeRy: 12, fluff: 0.35 },
  },
  'blue-gray': {
    id: 'cat-blue-gray',
    displayName: 'Blue Gray Cat',
    description: 'A high-resolution blue-gray cat companion with plush cool-toned fur.',
    breed: 'blue-gray',
    style: 'smooth-scaled plush blue gray companion with cool velvet shading',
    recommendedUse: 'focused pet, cool themes, and quiet desktop feedback',
    pattern: 'solid',
    shape: {
      faceWidth: 0.98,
      faceHeight: 1.0,
      earScale: 0.98,
      bodyWidth: 1.02,
      bodyHeight: 1.0,
      tailLength: 1.0,
      tailFluff: 1.04,
      pawScale: 1.0,
    },
    palette: {
      outline: '#28313e',
      furDark: '#536477',
      fur: '#75879a',
      furLight: '#aab8c6',
      cream: '#d8e0e8',
      blush: '#eba4ba',
      eye: '#142133',
      iris: '#7dc8c8',
    },
    details: { eyeDx: 17, eyeRx: 9, eyeRy: 11 },
  },
  cow: {
    id: 'cat-cow',
    displayName: 'Cow Cat',
    description: 'A high-resolution cow cat companion with playful black-and-white patches.',
    breed: 'cow',
    style: 'smooth-scaled playful cow cat companion with bold irregular patches',
    recommendedUse: 'comic pet, playful reactions, and high-contrast themes',
    pattern: 'cow',
    shape: {
      faceWidth: 1.04,
      faceHeight: 1.0,
      earScale: 0.96,
      bodyWidth: 1.04,
      bodyHeight: 1.0,
      tailLength: 1.02,
      tailFluff: 0.98,
      pawScale: 1.04,
    },
    palette: {
      outline: '#1c1d22',
      furDark: '#d5d4d0',
      fur: '#f3eee6',
      furLight: '#fffaf0',
      cream: '#fffdf5',
      blush: '#ffa8ba',
      eye: '#152033',
      iris: '#4f9a7b',
      patchB: '#1b1d22',
    },
    details: { eyeDx: 19, eyeRx: 11, eyeRy: 12, accent: 'milkdrop' },
  },
  tortie: {
    id: 'cat-tortie',
    displayName: 'Tortie Cat',
    description: 'A high-resolution tortoiseshell cat companion with tiny mottled patches.',
    breed: 'tortie',
    style: 'smooth-scaled tortoiseshell companion with warm mottled coat patches',
    recommendedUse: 'expressive pet, cozy reactions, and richly colored moods',
    pattern: 'tortie',
    shape: {
      faceWidth: 0.98,
      faceHeight: 1.02,
      earScale: 1.02,
      bodyWidth: 0.98,
      bodyHeight: 1.02,
      tailLength: 1.04,
      tailFluff: 1.0,
      pawScale: 0.98,
    },
    palette: {
      outline: '#251d1c',
      furDark: '#2a2421',
      fur: '#4b382d',
      furLight: '#7a5740',
      cream: '#c8925e',
      blush: '#e995a8',
      eye: '#121a28',
      iris: '#d49a45',
      patchA: '#c06a32',
      patchB: '#ddad6c',
    },
    details: { eyeDx: 18, eyeRx: 10, eyeRy: 11, fluff: 0.2 },
  },
  ragdoll: {
    id: 'cat-ragdoll',
    displayName: 'Ragdoll Cat',
    description: 'A high-resolution ragdoll cat companion with soft mitted point markings.',
    breed: 'ragdoll',
    style: 'smooth-scaled fluffy ragdoll companion with pale coat and soft point markings',
    recommendedUse: 'gentle pet, relaxed moods, and cozy desktop feedback',
    pattern: 'mitted',
    shape: {
      faceWidth: 1.1,
      faceHeight: 1.04,
      earScale: 0.9,
      bodyWidth: 1.12,
      bodyHeight: 1.02,
      tailLength: 1.08,
      tailFluff: 1.2,
      pawScale: 1.12,
    },
    palette: {
      outline: '#5c4a45',
      furDark: '#cbb9a8',
      fur: '#e7d6c2',
      furLight: '#fff0dc',
      cream: '#fff8ef',
      blush: '#ffadbd',
      eye: '#183457',
      iris: '#5da0d3',
      point: '#7c6158',
    },
    details: { eyeDx: 20, eyeRx: 11, eyeRy: 13, fluff: 0.85 },
  },
  snowshoe: {
    id: 'cat-snowshoe',
    displayName: 'Snowshoe Cat',
    description: 'A high-resolution snowshoe cat companion with dark points and bright white mitts.',
    breed: 'snowshoe',
    style: 'smooth-scaled snowshoe companion with crisp mittens and point markings',
    recommendedUse: 'smart pet, focused feedback, and crisp desktop themes',
    pattern: 'mitted',
    shape: {
      faceWidth: 0.96,
      faceHeight: 1.02,
      earScale: 1.04,
      bodyWidth: 0.96,
      bodyHeight: 1.04,
      tailLength: 1.12,
      tailFluff: 0.86,
      pawScale: 0.98,
    },
    palette: {
      outline: '#2d2528',
      furDark: '#76665e',
      fur: '#bda995',
      furLight: '#e6d8c9',
      cream: '#fff7ed',
      blush: '#eba0ad',
      eye: '#12304f',
      iris: '#4fa6c5',
      point: '#3f3132',
    },
    details: { eyeDx: 17, eyeRx: 9, eyeRy: 12, accent: 'milkdrop' },
  },
  lilac: {
    id: 'cat-lilac',
    displayName: 'Lilac Cat',
    description: 'A high-resolution lilac cat companion with soft lavender-gray shading.',
    breed: 'lilac',
    style: 'smooth-scaled lilac companion with muted lavender gray coat',
    recommendedUse: 'soft pet, pastel themes, and gentle reactions',
    pattern: 'solid',
    shape: {
      faceWidth: 1.02,
      faceHeight: 1.0,
      earScale: 0.96,
      bodyWidth: 1.02,
      bodyHeight: 0.98,
      tailLength: 0.98,
      tailFluff: 1.06,
      pawScale: 1.02,
    },
    palette: {
      outline: '#5a4f63',
      furDark: '#9b8fa3',
      fur: '#b9adbf',
      furLight: '#d8cfde',
      cream: '#f3edf5',
      blush: '#f1a6c3',
      eye: '#20243b',
      iris: '#9b7bd1',
    },
    details: { eyeDx: 19, eyeRx: 10, eyeRy: 12, fluff: 0.3 },
  },
};

const DEFAULT_BREED_ID = 'tabby';

function resolveBreed(id) {
  const normalized = String(id || DEFAULT_BREED_ID).trim().toLowerCase();
  const breed = CAT_BREEDS[normalized];
  if (!breed) {
    throw new Error(`unknown cat breed: ${id}`);
  }
  return breed;
}

module.exports = {
  CAT_BREEDS,
  DEFAULT_BREED_ID,
  resolveBreed,
};
