const CAT_BREEDS = {
  tabby: {
    id: 'cat-tabby',
    displayName: 'Tabby Cat',
    description: 'A high-resolution tabby cat companion with expressive status animations.',
    breed: 'tabby',
    style: 'smooth-scaled expressive orange tabby companion',
    recommendedUse: 'default pet, game reactions, and status feedback',
    pattern: 'tabby',
    shape: {
      faceWidth: 1.0,
      faceHeight: 1.0,
      earScale: 1.0,
      bodyWidth: 1.0,
      bodyHeight: 1.0,
      tailLength: 1.0,
      tailFluff: 1.0,
      pawScale: 1.0,
    },
    palette: {
      outline: '#3d2730',
      furDark: '#8e5b3d',
      fur: '#d88b52',
      furLight: '#ffd2a4',
      cream: '#fff0d6',
      blush: '#ff9db1',
      eye: '#1b2638',
    },
  },
  calico: {
    id: 'cat-calico',
    displayName: 'Calico Cat',
    description: 'A high-resolution calico cat companion with warm patchwork markings.',
    breed: 'calico',
    style: 'smooth-scaled expressive calico companion with patchwork coat markings',
    recommendedUse: 'colorful pet, cheerful reactions, and cozy desktop feedback',
    pattern: 'calico',
    shape: {
      faceWidth: 1.02,
      faceHeight: 1.0,
      earScale: 0.98,
      bodyWidth: 1.02,
      bodyHeight: 1.0,
      tailLength: 1.04,
      tailFluff: 1.08,
      pawScale: 1.02,
    },
    palette: {
      outline: '#34262a',
      furDark: '#2f2928',
      fur: '#f0b36b',
      furLight: '#fff1df',
      cream: '#fff8ef',
      blush: '#ff9fb4',
      eye: '#233149',
      patchA: '#d98539',
      patchB: '#2c2726',
    },
  },
  siamese: {
    id: 'cat-siamese',
    displayName: 'Siamese Cat',
    description: 'A high-resolution Siamese cat companion with point-color face, ears, paws, and tail.',
    breed: 'siamese',
    style: 'smooth-scaled expressive Siamese companion with cool blue-eyed point markings',
    recommendedUse: 'elegant pet, focused states, and calm desktop feedback',
    pattern: 'point',
    shape: {
      faceWidth: 0.88,
      faceHeight: 1.04,
      earScale: 1.18,
      bodyWidth: 0.90,
      bodyHeight: 1.08,
      tailLength: 1.18,
      tailFluff: 0.72,
      pawScale: 0.88,
    },
    palette: {
      outline: '#352822',
      furDark: '#5a4035',
      fur: '#d9c1a0',
      furLight: '#ead8bd',
      cream: '#f5e6ce',
      blush: '#d99a9e',
      eye: '#17324d',
      point: '#4a342d',
    },
  },
  tuxedo: {
    id: 'cat-tuxedo',
    displayName: 'Tuxedo Cat',
    description: 'A high-resolution tuxedo cat companion with sharp black-and-white contrast.',
    breed: 'tuxedo',
    style: 'smooth-scaled expressive tuxedo companion with white chest and face blaze',
    recommendedUse: 'crisp pet, terminal-adjacent themes, and status feedback',
    pattern: 'tuxedo',
    shape: {
      faceWidth: 0.98,
      faceHeight: 1.0,
      earScale: 1.0,
      bodyWidth: 1.0,
      bodyHeight: 1.02,
      tailLength: 0.98,
      tailFluff: 0.96,
      pawScale: 1.0,
    },
    palette: {
      outline: '#171a20',
      furDark: '#10141a',
      fur: '#202833',
      furLight: '#3a4654',
      cream: '#fff8ef',
      blush: '#f3a3b6',
      eye: '#101722',
    },
  },
  black: {
    id: 'cat-black',
    displayName: 'Black Cat',
    description: 'A high-resolution black cat companion with soft night-mode contrast.',
    breed: 'black',
    style: 'smooth-scaled expressive black cat companion with subtle charcoal highlights',
    recommendedUse: 'night mode pet, quiet focus, and compact desktop feedback',
    pattern: 'solid',
    shape: {
      faceWidth: 0.96,
      faceHeight: 0.98,
      earScale: 1.06,
      bodyWidth: 0.96,
      bodyHeight: 0.98,
      tailLength: 1.08,
      tailFluff: 0.92,
      pawScale: 0.95,
    },
    palette: {
      outline: '#080a10',
      furDark: '#11141d',
      fur: '#202638',
      furLight: '#3b435a',
      cream: '#30384d',
      blush: '#80596d',
      eye: '#0d1624',
    },
  },
  white: {
    id: 'cat-white',
    displayName: 'White Cat',
    description: 'A high-resolution white cat companion with gentle pale coat shading.',
    breed: 'white',
    style: 'smooth-scaled expressive white cat companion with soft cream shadows',
    recommendedUse: 'minimal pet, gentle moods, and clean desktop feedback',
    pattern: 'solid',
    shape: {
      faceWidth: 1.06,
      faceHeight: 1.02,
      earScale: 0.92,
      bodyWidth: 1.04,
      bodyHeight: 1.0,
      tailLength: 0.95,
      tailFluff: 1.04,
      pawScale: 1.04,
    },
    palette: {
      outline: '#6d5960',
      furDark: '#d7c7bd',
      fur: '#f4e8dc',
      furLight: '#fff8ef',
      cream: '#ffffff',
      blush: '#ffb4c4',
      eye: '#263454',
    },
  },
};

const DEFAULT_BREED_ID = 'tabby';

function resolveBreed(id) {
  const normalized = String(id || DEFAULT_BREED_ID).trim().toLowerCase();
  const breed = CAT_BREEDS[normalized];
  if (!breed) {
    throw new Error(`unknown cat breed: ${id}`);
  }
  return breed;
}

module.exports = {
  CAT_BREEDS,
  DEFAULT_BREED_ID,
  resolveBreed,
};
